language: node_js
node_js:
  "8"
after_success: ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive test/ && cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
